apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    purpose: work
    app: work
spec:
  containers:
    - name: worker
      image: nathanbenais/worker
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: '8080'
        - name: MULT
          value: 'true'
        - name: ADD
          value: 'true'
