apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-general
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
      type: general
  template:
    metadata:
      labels:
        app: worker
        type: general
    spec:
      containers:
        - name: worker
          image: nathanbenais/worker
          ports:
            - containerPort: 8080
          env:
            - name: PLANNER
              value: "http://planner:3000"
