apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mult
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
      type: mult
  template:
    metadata:
      labels:
        app: worker
        type: mult
    spec:
      containers:
        - name: worker
          image: nathanbenais/worker
          ports:
            - containerPort: 8080
          env:
            - name: PLANNER
              value: "http://planner:3000"
            - name: MULT
              value: "true"
            - name: ADD
              value: "false"
